name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-${increment}"
      id: version      
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
      run: |        
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "--- NEW VERSION $NEW_VERSION!!!"

    - name: Docker Build Image
      env:
        NEW_VERSION:   ${{ steps.version.outputs.version }}
      run: |
         docker build -t xreedit/ddgraphql:$NEW_VERSION .

    - name: Docker Push
      env:
        NEW_VERSION:   ${{ steps.version.outputs.version }}
      run: |
         docker push xreedit/ddgraphql:$NEW_VERSION
        

        
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
