name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |        
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Build Image
      run: |
         docker build -t xreedit/ddgraphql:0.0.2 .

    - name: Docker Push
      run: |
         docker push xreedit/ddgraphql:0.0.2 .
        

        
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
